- name: demo on register
  hosts: all
  tasks:
    - name: get uptime
      ansible.builtin.shell: uptime
      register: shell_output

    - name: print output
      ansible.builtin.debug:
        msg: "{{shell_output.stdout}}"

    - name: declare variable
      ansible.builtin.debug:
        uptime: "{{shell_output.stdout}}"



