- name: loop
  hosts: all
  tasks:
    - name: fruit name
      ansible.builtin.debug:
        msg: fruit name = {{ item }}
      loop:
        - banana
        - apple
    - name: fruit names with quantity
      ansible.builtin.debug:
        msg: fruit name = {{ item,name }}, quantity = {{ item.qty }}
      loop:
        - { name: banana, qty: 100}
        - { name: apple, qty: 200}